spring.datasource.url=jdbc:h2:file:../tms_db
quarkus.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.security.user.username=123
spring.security.user.password=123

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true

management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true

spring.h2.console.path=/console

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE